# -*- coding: utf-8 -*-
"""Script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WSMJ0A1os7JLxKgJdpbyATJFB8bMlm-X
"""

details = {"Name" : 'Abdulsalam Rukayat Abiola' , "gmail" : "abiola4rusul@gmail.com" , "biostack" :'genomics16S' , "slack_username" : '@Abdulsalam' }

print('\n'.join("{}: {}".format(k, v) for k, v in details.items()))

